# Generated by Django 5.0.6 on 2024-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('year_model', models.DateField()),
                ('detail', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
