# Generated by Django 5.0.6 on 2024-07-02 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='detail',
            new_name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
