# Generated by Django 5.0.6 on 2024-07-02 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rename_detail_car_description_car_price_car_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
